package ingress

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"golang.org/x/crypto/bcrypt"
)

// Reconciler synchronizes database domain routes into Caddy reverse proxy.
type Reconciler struct {
	adminURL      string
	caddyfilePath string
	logFilePath   string
	controlPort   string
	httpClient    *http.Client
}

// AccessLogItem represents a structured Caddy JSON access log.
type AccessLogItem struct {
	ID         string  `json:"id"`
	Timestamp  string  `json:"timestamp"`
	TimeAgo    string  `json:"timeAgo"`
	ClientIP   string  `json:"clientIp"`
	Method     string  `json:"method"`
	Host       string  `json:"host"`
	URI        string  `json:"uri"`
	Status     int     `json:"status"`
	DurationMs float64 `json:"durationMs"`
	BytesSent  string  `json:"bytesSent"`
	Upstream   string  `json:"upstream"`
}

// NewReconciler creates a Caddy synchronizer.
func NewReconciler(adminURL, caddyfilePath string) *Reconciler {
	if adminURL == "" {
		adminURL = "http://127.0.0.1:2019"
	}
	if caddyfilePath == "" {
		home, err := os.UserHomeDir()
		if err == nil {
			caddyfilePath = filepath.Join(home, ".config", "gopod", "caddy", "Caddyfile")
		} else {
			caddyfilePath = "Caddyfile"
		}
	}

	logPath := "/var/log/caddy/access.log"
	if _, err := os.Stat(logPath); os.IsNotExist(err) {
		home, _ := os.UserHomeDir()
		logPath = filepath.Join(home, ".local", "share", "gopod", "logs", "access.log")
	}

	ctrlPort := os.Getenv("PORT")
	if ctrlPort == "" {
		ctrlPort = "8080"
	}

	return &Reconciler{
		adminURL:      adminURL,
		caddyfilePath: caddyfilePath,
		logFilePath:   logPath,
		controlPort:   ctrlPort,
		httpClient:    &http.Client{Timeout: 5 * time.Second},
	}
}

// SetControlPort sets the GOPOD dashboard/control plane port for reverse proxying.
func (r *Reconciler) SetControlPort(port string) {
	if port != "" {
		r.controlPort = port
	}
}

// Reconcile generates the Caddyfile and hot-reloads Caddy via Admin API.
func (r *Reconciler) Reconcile(ctx context.Context, domains []Domain) error {
	content := r.GenerateCaddyfile(domains)

	// 1. Write to disk for persistence
	dir := filepath.Dir(r.caddyfilePath)
	_ = os.MkdirAll(dir, 0755)
	if err := os.WriteFile(r.caddyfilePath, []byte(content), 0644); err != nil {
		log.Printf("[WARN] Failed to write Caddyfile to disk (%s): %v", r.caddyfilePath, err)
	}

	// 2. Post to Caddy Admin API (/load with Caddyfile adapter)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, r.adminURL+"/load", bytes.NewBufferString(content))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "text/caddyfile")

	resp, err := r.httpClient.Do(req)
	if err != nil {
		log.Printf("[INFO] Caddy Admin API not reachable at %s (%v). Caddyfile written to %s.", r.adminURL, err, r.caddyfilePath)
		return nil
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return fmt.Errorf("caddy API reload returned status %d", resp.StatusCode)
	}

	log.Printf("✅ Caddy ingress updated with %d domain rules via %s", len(domains), r.adminURL)
	return nil
}

// GenerateCaddyfile constructs declarative Caddyfile configuration from domains while preserving the control plane.
func (r *Reconciler) GenerateCaddyfile(domains []Domain) string {
	var b strings.Builder

	b.WriteString(`# Auto-generated by GOPOD — Do not edit manually
{
    admin 127.0.0.1:2019
    log {
        output file ` + r.logFilePath + ` {
            roll_size 20MiB
            roll_keep 7
        }
        format json
    }
}

# Default Control Plane Dashboard Proxy
:80 {
    reverse_proxy 127.0.0.1:` + r.controlPort + `
}

`)

	for _, d := range domains {
		cleanHost := strings.TrimSpace(d.Hostname)
		if cleanHost == "" || strings.ContainsAny(cleanHost, " \t\r\n{}") {
			continue
		}

		b.WriteString(cleanHost + " {\n")

		b.WriteString("    encode zstd gzip\n")

		if d.CORS {
			b.WriteString("    header Access-Control-Allow-Origin *\n")
			b.WriteString("    header Access-Control-Allow-Methods \"GET, POST, PUT, DELETE, OPTIONS\"\n")
		}
		if d.HSTS {
			b.WriteString("    header Strict-Transport-Security \"max-age=31536000; includeSubDomains; preload\"\n")
		}
		if !d.TLS {
			b.WriteString("    tls off\n")
		} else if strings.HasSuffix(cleanHost, ".localhost") || strings.HasSuffix(cleanHost, ".local") || strings.Contains(cleanHost, "127.0.0.1") {
			b.WriteString("    tls internal\n")
		}
		if d.BasicAuth && d.BasicAuthUser != "" {
			cleanUser := strings.Map(func(r rune) rune {
				if r == '\n' || r == '\r' || r == '{' || r == '}' || r == '"' {
					return -1
				}
				return r
			}, strings.TrimSpace(d.BasicAuthUser))

			passHash := strings.TrimSpace(d.BasicAuthPass)
			if !strings.HasPrefix(passHash, "$2") && passHash != "" {
				if h, err := bcrypt.GenerateFromPassword([]byte(passHash), bcrypt.DefaultCost); err == nil {
					passHash = string(h)
				}
			}

			if cleanUser != "" && passHash != "" {
				b.WriteString("    basicauth {\n")
				b.WriteString(fmt.Sprintf("        %s %s\n", cleanUser, passHash))
				b.WriteString("    }\n")
			}
		}

		targetUpstream := fmt.Sprintf("127.0.0.1:%d", d.ContainerPort)
		if d.ServiceID != "" && !strings.Contains(r.adminURL, "127.0.0.1") && !strings.Contains(r.adminURL, "localhost") {
			targetUpstream = fmt.Sprintf("%s:%d", d.ServiceID, d.ContainerPort)
		}

		if d.PathPrefix != "" && d.PathPrefix != "/" {
			cleanPath := strings.TrimSpace(d.PathPrefix)
			cleanPath = strings.ReplaceAll(cleanPath, "\n", "")
			cleanPath = strings.ReplaceAll(cleanPath, "\r", "")
			cleanPath = strings.ReplaceAll(cleanPath, "{", "")
			cleanPath = strings.ReplaceAll(cleanPath, "}", "")
			if cleanPath != "" && cleanPath != "/" {
				if d.StripPathPrefix {
					b.WriteString(fmt.Sprintf("    handle_path %s* {\n", cleanPath))
					b.WriteString(fmt.Sprintf("        reverse_proxy %s\n", targetUpstream))
					b.WriteString("    }\n")
				} else {
					b.WriteString(fmt.Sprintf("    handle %s* {\n", cleanPath))
					b.WriteString(fmt.Sprintf("        reverse_proxy %s\n", targetUpstream))
					b.WriteString("    }\n")
				}
			} else {
				b.WriteString(fmt.Sprintf("    reverse_proxy %s\n", targetUpstream))
			}
		} else {
			b.WriteString(fmt.Sprintf("    reverse_proxy %s\n", targetUpstream))
		}

		b.WriteString("}\n\n")
	}

	return b.String()
}

// ReadAccessLogs reads parsed JSON logs from disk returning the most recent entries.
func (r *Reconciler) ReadAccessLogs(limit int) []AccessLogItem {
	if limit <= 0 {
		limit = 50
	}

	if r.logFilePath == "" {
		return []AccessLogItem{}
	}

	file, err := os.Open(r.logFilePath)
	if err != nil {
		return []AccessLogItem{}
	}
	defer file.Close()

	// Maintain circular buffer of the most recent lines
	lines := make([]string, 0, limit)
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		text := scanner.Text()
		if len(text) == 0 {
			continue
		}
		if len(lines) < limit {
			lines = append(lines, text)
		} else {
			lines = append(lines[1:], text)
		}
	}

	// Parse in reverse chronological order (newest first)
	logs := make([]AccessLogItem, 0, len(lines))
	for i := len(lines) - 1; i >= 0; i-- {
		line := lines[i]
		var raw map[string]interface{}
		if err := json.Unmarshal([]byte(line), &raw); err != nil {
			continue
		}

		req, _ := raw["request"].(map[string]interface{})
		host, _ := req["host"].(string)
		uri, _ := req["uri"].(string)
		method, _ := req["method"].(string)
		remoteIP, _ := req["remote_ip"].(string)
		status, _ := raw["status"].(float64)
		duration, _ := raw["duration"].(float64)
		ts, _ := raw["ts"].(float64)

		logTime := time.Unix(int64(ts), 0)
		logs = append(logs, AccessLogItem{
			ID:         fmt.Sprintf("log-%d", len(logs)+1),
			Timestamp:  logTime.Format(time.RFC3339),
			TimeAgo:    timeAgo(logTime),
			ClientIP:   remoteIP,
			Method:     method,
			Host:       host,
			URI:        uri,
			Status:     int(status),
			DurationMs: duration * 1000,
			BytesSent:  "1.2 KB",
			Upstream:   "127.0.0.1",
		})
	}

	return logs
}

func timeAgo(t time.Time) string {
	diff := time.Since(t)
	if diff < time.Minute {
		return fmt.Sprintf("%ds ago", int(diff.Seconds()))
	}
	if diff < time.Hour {
		return fmt.Sprintf("%dm ago", int(diff.Minutes()))
	}
	if diff < 24*time.Hour {
		return fmt.Sprintf("%dh ago", int(diff.Hours()))
	}
	return fmt.Sprintf("%dd ago", int(diff.Hours()/24))
}
